### ISSUE TITLE
Prompt Engineering

### ISSUE THREAD

**Issue by lakruzz** [Rasmus2103/Eksamensprojekt#1]
Sure, here's the transcript of our entire conversation in markdown format:

yaml
Copy code
## Question

In GitHub Action I want to create a continuous integration that triggers on any branch this isn't main - and the test if the branch can be rebased agains main, build using 'mvn clean package' and if that is successful push back to github 'origin master'

## Answer

You can create a GitHub Actions workflow to achieve this. Here's an example workflow that should meet your requirements:

```yaml
name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if branch can be rebased against main
        run: |
          git fetch
          if ! git rebase --onto main HEAD~1; then
            echo "Branch cannot be rebased against main. Please merge main into your branch before pushing again." >&2
            exit 1
          fi
      - name: Build with Maven
        run: mvn clean package
      - name: Push changes to main branch
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
```

This workflow uses the on.push event to trigger on any branch except for main. It then checks out the code, checks if the branch can be rebased against main, builds the code with Maven, and pushes the changes back to the main branch using the ad-m/github-push-action GitHub Action.

Note that this workflow uses the secrets.GITHUB_TOKEN token to authenticate with GitHub, which is automatically created by GitHub and should be available in your workflow environment. Also, you may need to adjust the branch names in the workflow to match your repository's naming conventions.

Follow-up question
Isn't it true that actions/checkout default clones using depth=1 - so a fetch would never work - I need to checkout the full repo

Follow-up answer
Yes, you're correct. The actions/checkout action defaults to cloning with --depth=1, which means that the entire history of the repository is not downloaded. As a result, a subsequent git fetch command would not work as expected.

To ensure that the full repository is checked out, you can add the fetch-depth: 0 option to the actions/checkout step. Here's the updated workflow:

```yaml
name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if branch can be rebased against main
        run: |
          git fetch
          if ! git rebase --onto main HEAD~1; then
            echo "Branch cannot be rebased against main. Please merge main into your branch before pushing again." >&2
            exit 1
          fi
      - name: Build with Maven
        run: mvn clean package
      - name: Push changes to main branch
        if: ${{ success() }}
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
```
In this updated workflow, the fetch-depth: 0 option is added to the actions/checkout step to ensure that the full repository
